name: Checkmarx AST Scan

on:
  push:
    branches:
    - main
    - master
    - develop
    - 'feature/*'

  pull_request:
    branches:
    - main
    - develop

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
    
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.3.36
        with:
          base_uri: https://ast.checkmarx.net
          cx_tenant: YOUR_TENANT_NAME
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
    
          project_name: My-Application
          branch: ${{ github.head_ref || github.ref_name }}
    
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
          source_dir: .
    
          scan_params: >
            --sast
            --sca
            --iac-security
            --container-security
    
          results_params: >
            --report-format json
    
          repo_name: ${{ github.event.repository.name }}
          namespace: ${{ github.repository_owner }}
          pr_number: ${{ github.event.number }}
